USE master
GO

IF EXISTS(SELECT * FROM sys.databases WHERE NAME = 'Exercises')
	DROP DATABASE [Exercises]

CREATE DATABASE [Exercises]
GO

USE [Exercises]
GO

CREATE TABLE [DEPARTMENTS] (
	[Code] VARCHAR(5) PRIMARY KEY,
	[NAME] VARCHAR(100) NOT NULL
)
GO

CREATE TABLE [Employees] (
	[ID] BIGINT PRIMARY KEY IDENTITY(1,1),
	[FirstName] VARCHAR(100) NOT NULL,
	[MiddleName] VARCHAR(100) NULL,
	[LastName] VARCHAR(100) NULL,
	[BirthDay] DATE NOT NULL,
	[CPF] VARCHAR(11) UNIQUE NOT NULL,
	[RG] VARCHAR(11) UNIQUE NOT NULL,
	[Address] VARCHAR(100) NOT NULL,
	[CEP] VARCHAR(8) NOT NULL,
	[City] VARCHAR(100) NOT NULL,
	[PhoneNumber] VARCHAR(13) NOT NULL,
	[CodeDepartment] VARCHAR(5) REFERENCES [DEPARTMENTS](Code) NOT NULL,
	[Wage] DECIMAL NOT NULL
)
GO