CREATE VIEW VIEW_VENDAS AS 
SELECT TC.NOME AS CLIENTES, TV.NOME AS VENDEDORES, TP.[NOME DO PRODUTO] AS PRODUTOS, INF.QUANTIDADE AS QUANTIDADE,
INF.PREÇO AS PREÇO, NF.[DATA] FROM [TABELA DE CLIENTES] TC
JOIN [NOTAS FISCAIS] NF ON TC.CPF = NF.CPF
JOIN [TABELA DE VENDEDORES] TV ON TV.MATRICULA = NF.MATRICULA
JOIN [ITENS NOTAS FISCAIS] INF ON INF.NUMERO = NF.NUMERO
JOIN [TABELA DE PRODUTOS] TP ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
 
SELECT * FROM VIEW_VENDAS
---

SELECT TV.NOME AS VENDEDORES, SUM(INF.PREÇO) AS PREÇO, NF.[DATA] FROM [TABELA DE CLIENTES] TC
JOIN [NOTAS FISCAIS] NF ON TC.CPF = NF.CPF
JOIN [TABELA DE VENDEDORES] TV ON TV.MATRICULA = NF.MATRICULA
JOIN [ITENS NOTAS FISCAIS] INF ON INF.NUMERO = NF.NUMERO
GROUP BY TV.NOME, NF.[DATA]

---

Alter PROCEDURE BUSCA_POR_ENTIDADE @ENTIDADE VARCHAR(10)
AS BEGIN
	IF @ENTIDADE = 'cliente'
		SELECT * FROM [TABELA DE CLIENTES]
	ELSE IF @ENTIDADE = 'vendedor'
		SELECT * FROM [TABELA DE VENDEDORES]
END

EXECUTE BUSCA_POR_ENTIDADE 'cliente'
EXECUTE BUSCA_POR_ENTIDADE 'vendedor'

--Crie uma procedure que receba por parametro um CPF e uma Data de inicio e uma de fim e mostre as notas fiscais deste CPF
--e que este jam entre assas datas

create proc busca_por_CPF
@cpf varchar(11),
@datao date,
@data date
as begin
select * from [NOTAS FISCAIS]
where CPF = @cpf and [DATA] between @datao and @data
end

exec busca_por_CPF '50534475787', '2015-01-01', '2016-01-01'